### ISSUE TITLE
Github Actions node_modules cache 중 오류 핸들링 과정

### ISSUE THREAD

**Issue by heartane** [heartane/Lumiere-backend#31]
> 해결된 에러라면 라벨에 'Complete' 를 달아주세요.
> 미해결된 에러라면 라벨을 'In progress' 로 변경해주세요.

### 

- PR CI를 돌리면서 install dependencies에서 시간이 오래걸린다는 것을 확인했다.
npm install보다 CI에 더 적합한 npm ci를 사용하지만, 매번 node_modules를 삭제하고 다시 설치하는 것보다는 
기존에 캐싱된 node_modules가 있다면 넘어갈 수 있도록 npm cache에 대해 찾아보고 적용하게 되었다.

```yml
jobs:
  ci:
    name: eslint & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - if: steps.npm-cache.outputs.cache-hit == 'true'
        run: echo 'npm cache hit!'
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run build --if-present
      - name: Eslint
        run: npm run lint
      - name: Test
```
### 어떤 에러인가요?
- 첫 job을 run하면 캐시가 되지 않으니 정상적으로 작동했지만, re-run을 해보면서 문제가 생겼다.

### 에러 메시지
<img width="694" alt="Screen Shot 2022-07-07 at 01 41 51 AM" src="https://user-images.githubusercontent.com/85835375/177688401-b9c420e1-a97c-4d0c-9129-f23ea9f877d3.png">

### 에러 핸들링 방법

- package.json scripts lint 실행 명령어에 경로를 써 놨는데 이를 감지하지 못하는 것 같았다.
- 캐시 경로가 ~/.npm인데 lint 실행 명령어 경로와 상이해서 문제가 되는 것 같아 캐시 경로를 수정해주었다.

```yml
steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache dependencies
        uses: actions/cache@v3
        id: node-cache
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - if: steps.node-cache.outputs.cache-hit == 'true'
        run: echo 'node cache hit!'
      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run build --if-present
      - name: Eslint
        run: npm run lint
      - name: Test
```
- 캐시 경로를 node_modules로 변경하니 첫 run에서는 npm ci를 진행하고, re-run은 캐시값으로 정상 실행이 된다.
- 또한 그 실행 시간이 1분 남짓에서 33초로 2배나 빨라졌다...!
### 에러 핸들링을 위해 참고한 레퍼런스 링크
- [Caching dependencies to speed up workflows](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows)
